application: applicationid
version: 0-0-0
runtime: python27
api_version: 1
threadsafe: yes

handlers:
# APP STATS
- url: /stats(/.*)?
  script: google.appengine.ext.appstats.ui.app
  login: admin

# API SCRIPT
- url: .*
  script: api.app

# LIBRARIES
libraries:
- name: webapp2
  version: "2.5.1"
- name: pycrypto
  version: "2.6"
- name: PIL
  version: "1.1.7"

builtins:
- appstats: on
- remote_api: on